### ISSUE TITLE
LOG_LEVEL

### ISSUE THREAD

**Issue by geooogle** [kpetremann/mqtt-exporter#21]
Hello, and I love your image!!

Was wondering what the level options for LOG_LEVEL are? I was looking for scraping everything from my broker, kinda like verbose. I didnt look hard enough in your code but I tried to find how to export basically `#`. thank you! and great app

**Comment by kpetremann** [comment]
Hello @geooogle,

LOG_LEVEL can be one of these values:  DEBUG, INFO, WARNING, ERROR, CRITICAL

FYI, they can be found here: https://docs.python.org/3/library/logging.html#logging-levels (you don't need to put the numeric value, the string value is enough)

**Comment by geooogle** [comment]
Merci. I appreciate this!
