### ISSUE TITLE
Actions: Docker image tags

### ISSUE THREAD

**Issue by kpetremann** [kpetremann/mqtt-exporter#34]
Issue to track the request from https://github.com/kpetremann/mqtt-exporter/issues/32#issuecomment-1228749043

Improve docker image release workflow by pushing tags

**Comment by onedr0p** [comment]
Hi @kpetremann it would also be great if you could push your image to the Github Container registry.

I have opened a PR here https://github.com/kpetremann/mqtt-exporter/pull/39

**Comment by kpetremann** [comment]
Hi @onedr0p, sure why not. I'll have a look next week.

Out of curiosity, why would you like to have it in Github Container Registry as well? the usual docker registry is working fine.

**Comment by onedr0p** [comment]
Because dockerhub has aggressive rate limits, 100 pulls per 6 hours for unauthenticated and 200 pulls per 6 hours for authenticated pulls. Dockerhub also has aggressive retention limits too.

**Comment by kpetremann** [comment]
Docker images are now pushed with tags:

    "master" tag when only pushing or merging PR to the master
    "1.2.3", "1.2", "1" and "latest" tags when pushing a tagged version

**Comment by onedr0p** [comment]
This is awesome, thanks!
