### ISSUE TITLE
Tag docker images with release version number

### ISSUE THREAD

**Issue by bmurphy1976** [kpetremann/mqtt-exporter#38]
Any chance we can get the docker hub images tagged with the associated release version number?

**Comment by kpetremann** [comment]
Hello @bmurphy1976,

There is already an issue tracked here #34.

I did not have time yet to do it yet.

PS: I am closing this issue as it is a duplicated. Don't hesitate to follow-up on #34.

Thanks

**Comment by bmurphy1976** [comment]
Sorry for the dupe and thanks for the pointer.  Totally missed the existing request!

**Comment by kpetremann** [comment]
No problem 👍

**Comment by kpetremann** [comment]
@bmurphy1976 in case you are not watching the other issue, tags are now pushed.

**Comment by bmurphy1976** [comment]
Awesome, thank you!  I see the tags!
