### ISSUE TITLE
Support esphome format

### ISSUE THREAD

**Issue by zoic21** [kpetremann/mqtt-exporter#49]
Hello,

I have lot of esphome device and I want to transfert data from esphome to prometheus, I try mqtt-exporter but format of mqtt message of esphome is not supported, example of topic : 
`esp-weather-outdoor/sensor/temperature/state` => 8.1

It's like `<prefix>/<name>/sensor/temperature` (shelly) but with state at the end.

Is it possible to handle that ?

Thank in advance.

**Comment by kpetremann** [comment]
hello @zoic21,

Sure, I can try. 

I am not familiar with esphome: is the prefix always the same? has it a default value?

I will also check the documentation.

**Comment by kpetremann** [comment]
note: I cannot simply use "/state" suffix in the topic to identify esphome message. 
This would cause collision with other zigbee2mqtt messages, using state as a type of value (for an ON/OFF button for instance).

**Comment by zoic21** [comment]
Hello,

Yes it's always the same. Maybe to prevent issue with zigbee2mqtt you can add an env variable that indicates root topic of zigbee2mqtt?

Thank in advance

**Comment by kpetremann** [comment]
I agree, this was exactly my intent :)

I just needed to know if there was a default value. According esphome documentation, the default seems to be the node name.
If the varenv is empty, it will not enter the esphome "parsing" function.

I'll push a commit for you to test tomorrow.

**Comment by kpetremann** [comment]
Hello @zoic21,

Please let me know if the code in the branch [esphome](https://github.com/kpetremann/mqtt-exporter/tree/esphome) works for you.

**Comment by zoic21** [comment]
Hello,

Thank it's work but how can I specify multiple esphome root topic. In Esphome each device create a topic in root of mqtt. For example I have 6 devices, each device have a "root" topic, ex : esp-weather-indoor/esp-weather-outdoor/....

**Comment by zoic21** [comment]
Hello,

Thank a lot !!!! it's perfectly works !!!! With that I can have all my mqtt data in grafana.

Thank a lot.

**Comment by kpetremann** [comment]
No problem.

I'll merge that to the master branch later and it will be in the next release.

**Comment by kpetremann** [comment]
FYI it has been merged and officially released in the new v1.1.0.

Enjoy 🙂
