### ISSUE TITLE
Hubitat support

### ISSUE THREAD

**Issue by michalzxc** [kpetremann/mqtt-exporter#57]
I configured Hubitat Zigbee hub with https://community.hubitat.com/t/beta-yama-yet-another-mqtt-app/62219

I am trying to export metrics it produces to Prometheus
![image](https://github.com/kpetremann/mqtt-exporter/assets/1896427/0f2f1bed-cd6c-4958-a3fe-b01865bbc1a6)
Specially I am interested in power metrics:
![image](https://github.com/kpetremann/mqtt-exporter/assets/1896427/df05368c-f97d-4de9-93f9-c1eb0e637757)

**Comment by kpetremann** [comment]
hi @michalzxc,

Could you please provide the MQTT original topic + payload please?

It should look like:
```topic '<prefix>/<name>', payload '{"temperature":26.24,"humidity":45.37}'```
or
```topic '<prefix>/<name>/sensor/temperature' '20.00'```

Also please elaborate on the problem: is it crashing or just not exposing the metrics?

**Comment by michalzxc** [comment]
It is not exposing it

<prefix=hubitat>/<hub name=home-hub>/<device name, including spaces>/"attributes"/<name>/"value"

Inside "value" there is an actual value, not JSON, but raw

**Comment by kpetremann** [comment]
thanks
do you mean that the value is in the topic and not in the payload?

**Comment by kpetremann** [comment]
ok I got a look to the doc you provided.

Can you please try using the [hubitat_support](https://github.com/kpetremann/mqtt-exporter/tree/hubitat_support) branch please?

**Comment by michalzxc** [comment]
The entire topic for power consumption for device called "PC Power Switch":
```
hubitat/home-hub/PC Power Switch/attributes/power/value
```

Voltage is here:
```
hubitat/home-hub/PC Power Switch/attributes/voltage/value
```

Inside of the first one there is RAW output with 7, representing 7W.

Picture from MQTT Explorer:
![image](https://github.com/kpetremann/mqtt-exporter/assets/1896427/5c0959f5-d875-469d-9b6c-3ed507606fda)

On/Off example:
I have topic
```
hubitat/home-hub/Storage light/attributes/switch/value
```
It has value `on` what means light is on, if I want to turn it off I need to publish payload `off` to hubitat/home-hub/Storage light/attributes/switch/value
![image](https://github.com/kpetremann/mqtt-exporter/assets/1896427/b8c73df5-2aa8-4c46-ad10-2af9e15fa6a2)

**Comment by michalzxc** [comment]
Building container from hubitat branch

In yours example, what you called "some room" is actually a "device name"
And temperature should be under `attributes` string

**Comment by kpetremann** [comment]
> In yours example, what you called "some room" is actually a "device name"

yes, a device usually is room in my example, so don't worry for this one.

>  And temperature should be under attributes string

did you do something custom?
because the [doc](https://community.hubitat.com/t/beta-yama-yet-another-mqtt-app/62219) you provided says that the metrics look like:
```hubitat/[hubname]/[device name]/[attribute name]/value```

**Comment by michalzxc** [comment]
```
hubitat/[hubname]/[device name]/attributes/[attribute name]/value
```

Like for example:
```
hubitat/home-hub/PC Power Switch/attributes/power/value
````

There is static `attributes` as a string here

**Comment by michalzxc** [comment]
I did nothing custom, it doesn't really have any configuration options:
![image](https://github.com/kpetremann/mqtt-exporter/assets/1896427/3b47a262-8913-4410-86ff-fbc21cdac2cf)
![image](https://github.com/kpetremann/mqtt-exporter/assets/1896427/651bd737-465d-42a8-9e58-8db13d2bf7d0)

**Comment by michalzxc** [comment]
IP, username, password, and selecting devices to expose, that is all that I can configure here

**Comment by michalzxc** [comment]
https://github.com/Botched1/Hubitat/tree/master/Apps/YAMA

**Comment by kpetremann** [comment]
actually it works with both:
```
hubitat/[hubname]/[device name]/[attribute name]/value
hubitat/[hubname]/[device name]/attributes/[attribute name]/value
```

So all good in any case.
I've updated the [branch](https://github.com/kpetremann/mqtt-exporter/tree/hubitat_support) to remove a breakpoint and to update the test.

Please test and let me know if it works for you.

**Comment by michalzxc** [comment]
Actually, it doesn't really say what attribute it is ?
```
mqtt_message_total{topic="hubitat_home-hub_pc power switch"} 7.0
```
I know that is power usage, but it does't say that

**Comment by michalzxc** [comment]
`pc power switch` is the name of the device, and 7 comes from `attributes/power/value`

**Comment by michalzxc** [comment]
```
mqtt_lastCheckinEpoch{topic="hubitat_home-hub_living room main light"}   1688145320304
```
Came from
````
hubitat/home-hub/living room main light/attributes/lastCheckinEpoch
```

**Comment by michalzxc** [comment]
I confused myself in last couple of comments, it is all good :) Thank you again

**Comment by kpetremann** [comment]
sounds great! :tada:

I'll merge the branch and do the release.

**Comment by kpetremann** [comment]
v1.3.0 released
