### ISSUE TITLE
UserProperty attribute exception

### ISSUE THREAD

**Issue by kpetremann** [kpetremann/mqtt-exporter#66]
see the comment here: https://github.com/kpetremann/mqtt-exporter/pull/65#issuecomment-1870227700

caused by #65.

**Comment by kpetremann** [comment]
hello @janpfischer,
The fix has been merged and is now available in v1.4.1.
On my side it has solved the issue. Please let me know if it works for you.

**Comment by janpfischer** [comment]
Yes, it is fixed for me too. Thank you for your very quick fix!

**Comment by kpetremann** [comment]
Perfect!
You are welcome :)
