### ISSUE TITLE
two additional projects can be added to supported projects

### ISSUE THREAD

**Issue by philippbussche** [kpetremann/mqtt-exporter#69]
Hi,

I have the mqtt-exporter running and I am using it to receive and expose metrics from:

https://github.com/jomjol/AI-on-the-edge-device
https://github.com/kbialek/deye-inverter-mqtt

For the latter I just had to set KEEP_FULL_TOPIC=True

Maybe you want to add them to your supported projects list.

Philipp

**Comment by kpetremann** [comment]
Hi @philippbussche,

Thanks for the info! I'll add it to the list in the README :)
