### ISSUE TITLE
Binary states from esphome fails to parse

### ISSUE THREAD

**Issue by mortenlj** [kpetremann/mqtt-exporter#82]
**Describe the bug**
When using a binary sensor in esphome, the payload is simply `ON` or `OFF`.
When parsing metrics, these values are handled by the `STATE_VALUES` map, but since these payloads aren't valid JSON, it never gets that far.

**To Reproduce**
1. Publish a message with the payload `ON`, and see how mqtt-exporter handles it.

**Expected behavior**
If the payload is one of the defined `STATE_VALUES`, it should parse it even if it isn't valid JSON.

**Additional context**
I looked quickly at how to resolve this, but the code got somewhat ugly, so not going to attempt a PR with the time I have available at the moment.

**Comment by kpetremann** [comment]
hi @mortenlj,

Thanks for raising the issue.

I have four questions:
- was it working before and stopped to work, or did it never worked?
- please provide the MQTT message and the logs so I can troubleshoot the issue.
- did you try the tool to test the conversion? see [here](https://github.com/kpetremann/mqtt-exporter?tab=readme-ov-file#cli-interactive-test)
- are you using the supported format `<TOPIC_PREFIX>/<COMPONENT_TYPE>/<COMPONENT_NAME>/state` (see [here](https://github.com/kpetremann/mqtt-exporter?tab=readme-ov-file#esphome))

**Comment by mortenlj** [comment]
> * was it working before and stopped to work, or did it never worked?

Never worked as far as I can tell.

> * please provide the MQTT message and the logs so I can troubleshoot the issue.

```
{
	"tst":	"2024-05-15T12:48:56.369786+0200",
	"topic":	"freezer_open_detector/binary_sensor/freezer_open/state",
	"qos":	0,
	"retain":	1,
	"payloadlen":	3,
	"payload":	"OFF"
}
```

> * did you try the tool to test the conversion?

I ran mqtt-exporter in a debugger and stopped it where the error occured, inside `_parse_message`. I got a `JSONDecodeError`, which results in a debug log and a parse result of `None, None`.

Ran the test tool now, and strangely got a different error:

```
topic: freezer_open_detector/binary_sensor/freezer_open/state
payload: OFF

## Debug ##

parsed to: None None
Traceback (most recent call last):
  File "/home/mortenlj/code/other/kpetremann/mqtt-exporter/./exporter.py", line 6, in <module>
    main()
  File "/home/mortenlj/code/other/kpetremann/mqtt-exporter/mqtt_exporter/main.py", line 494, in main
    _parse_metrics(payload, topic, "", labels=None)
  File "/home/mortenlj/code/other/kpetremann/mqtt-exporter/mqtt_exporter/main.py", line 177, in _parse_metrics
    for metric, value in data.items():
                         ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
```

> * are you using the supported format `<TOPIC_PREFIX>/<COMPONENT_TYPE>/<COMPONENT_NAME>/state`

Yes.

**Comment by kpetremann** [comment]
Thanks for all the details! I'll have a look

**Comment by mortenlj** [comment]
I suddenly found myself with some free time today, so I made a stab at fixing this.

**Comment by kpetremann** [comment]
awesome thanks, having a look

**Comment by kpetremann** [comment]
closing the issue as your PR has been merged.
Thanks again for your contribution!
