### ISSUE TITLE
Timeout on value

### ISSUE THREAD

**Issue by zoic21** [kpetremann/mqtt-exporter#86]
Hello

Thanks for the exporter it’s very usefull !!!!! CAN you add a timeout on value, for exemple I send temperture on mqtt each minute but if I stop the send mqtt exporter continue to expose my sensor temperature. 

What I want it’s a paramètre to define lifetime of value. With that it’s will be mark as no data in grafana and I can get an alert. 

Thanks in advance.

**Comment by bo0tzz** [comment]
This could also be an alternative resolution to #68

**Comment by kpetremann** [comment]
hello @zoic21,

I am glad it useful to you :)
Looking into it.

hello @bo0tzz,
got it.

**Comment by kpetremann** [comment]
@zoic21 @bo0tzz does PR #87 work for you?

**Comment by bo0tzz** [comment]
It feels a bit hacky (not your fault) but should do the job I think

**Comment by zoic21** [comment]
Hello
Sorry for delay, yes I can used that just and manage alert with this timestamp

**Comment by kpetremann** [comment]
Closing this issue: PR merged, the new feature is available in the latest version.
Feel free to reopen the issue if needed.
Cheers
